version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: words_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordsdb
      MYSQL_USER: worduser
      MYSQL_PASSWORD: wordpassword
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    networks:
      - words-network
    ports:
      - "2722:3306"

networks:
  words-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local

